// ============================================================
//  src/models/Task.js — Task schema (per-user isolation)
// ============================================================
const mongoose = require('mongoose');

const TaskSchema = new mongoose.Schema({
  userId: {
    type:     mongoose.Schema.Types.ObjectId,
    ref:      'User',
    required: true,
    index:    true
  },
  title: {
    type:      String,
    required:  [true, 'Title is required'],
    trim:      true,
    maxlength: [200, 'Title max 200 chars']
  },
  desc: {
    type:    String,
    default: '',
    trim:    true
  },
  category: {
    type:    String,
    enum:    ['Design', 'Engineering', 'Marketing', 'Research', 'Other'],
    default: 'Other'
  },
  status: {
    type:    String,
    enum:    ['todo', 'inprogress', 'done'],
    default: 'todo'
  },
  priority: {
    type:    String,
    enum:    ['low', 'medium', 'high'],
    default: 'medium'
  },
  deadline: {
    type:    Date,
    default: null
  },
  gptEnhanced: {
    type:    Boolean,
    default: false
  },
  // Subtasks generated by GPT
  subtasks: [{
    title:     String,
    completed: { type: Boolean, default: false }
  }],
  // GPT priority analysis result
  aiAnalysis: {
    priority:       String,
    score:          Number,
    reasoning:      String,
    analyzedAt:     Date
  },
  // Track reminders sent
  reminderSentAt: Date
}, { timestamps: true });

// Indexes for common query patterns
TaskSchema.index({ userId: 1, status: 1 });
TaskSchema.index({ userId: 1, deadline: 1 });
TaskSchema.index({ userId: 1, category: 1 });

module.exports = mongoose.model('Task', TaskSchema);
